In [1]:
import re

import pandas as pd
pd.set_option('display.max_rows', None)

from astroquery.simbad import Simbad

In [2]:
def extract_ngc_id(name):
    """
    Extract the NGC ID and friendly name from the given string.
    
    Parameters:
        name (str): The string from which to extract the NGC ID and friendly name.
        
    Returns:
        tuple: (ngc_id, friendly_name) where both are strings or None.
    """
    # Regex to extract NGC ID format, considering 'NGC ' followed by digits
    ngc_pattern = re.compile(r'(NGC \d+)(/[\d]+)?')
    ngc_match = ngc_pattern.search(name)
    
    # Extract NGC ID
    ngc_id = ngc_match.group(1) if ngc_match else None
    
    # Extract friendly name
    if ngc_id:
        friendly_name = name.replace(ngc_id, '').replace(ngc_match.group(2) if ngc_match.group(2) else '', '').strip() or None
    else:
        friendly_name = name.strip() or None
    
    return ngc_id, friendly_name

def get_friendly_name(ngc_id):
    friendly_name = None
    try:
        result_table = Simbad.query_objectids(ngc_id)
        if result_table is not None:
            names = [name[5:] for name in result_table['ID'] if name.startswith("NAME")]
            if names:
                friendly_name = max(names, key=len)

    except Exception as e:
        print(f"An error occurred while querying {ngc_id}: {str(e)}")
    return friendly_name

def convert_magnitude(value):
    try:
        return float(value)
    except (ValueError, TypeError):
        return pd.NA
    

def map_default_image(type_str):
    default_image_mapping = {
        'Star': 'star',
        'Open Cluster': 'cluster',
        'Globular Cluster': 'cluster',
        'Planetary Nebula': 'nebula',
        'Bright Nebula': 'nebula',
        'Diffuse Nebula': 'nebula',
        'Dark Nebula': 'nebula',
        'Supernova Remnant': 'nebula',
        'Spiral Galaxy': 'galaxy',
        'Elliptical Galaxy': 'galaxy',
        'Irregular Galaxy': 'galaxy',
        'Lenticular (S0) Galaxy': 'galaxy',
        'Star Cloud': 'star',
        'Double Star': 'star',
        'Group/Asterism': 'star'
    }
    return default_image_mapping.get(type_str, 'default')


def map_constellation(constellation_abbreviation):
    constellation_map = {
        'Cep': 'Cepheus', 'Dra': 'Draco', 'Cam': 'Camelopardalis', 'Cas': 'Cassiopeia',
        'Per': 'Perseus', 'Cyg': 'Cygnus', 'Lac': 'Lacerta', 'CVn': 'Canes Venatici',
        'And': 'Andromeda', 'Lyn': 'Lynx', 'Peg': 'Pegasus', 'Aur': 'Auriga',
        'Com': 'Coma Berenices', 'Vul': 'Vulpecula', 'Gem': 'Gemini', 'Leo': 'Leo',
        'Tau': 'Taurus', 'Del': 'Delphinus', 'Boo': 'Boötes', 'Mon': 'Monoceros',
        'Can': 'Canes Major', 'Cet': 'Cetus', 'Vir': 'Virgo', 'Sex': 'Sextans',
        'Aqr': 'Aquarius', 'Sgr': 'Sagittarius', 'CMa': 'Canis Major', 'Hya': 'Hydra',
        'Crv': 'Corvus', 'Scl': 'Sculptor', 'For': 'Fornax', 'CrA': 'Corona Australis',
        'Sco': 'Scorpius', 'Pup': 'Puppis', 'Col': 'Columba', 'Vel': 'Vela',
        'Cen': 'Centaurus', 'Ara': 'Ara', 'Hor': 'Horologium', 'Cir': 'Circinus',
        'Nor': 'Norma', 'Car': 'Carina', 'Pav': 'Pavo', 'Cru': 'Crux',
        'TrA': 'Triangulum Australe', 'Dor': 'Dorado', 'Tuc': 'Tucana', 'Mus': 'Musca',
        'Aps': 'Apus', 'Cha': 'Chamaeleon', 'Eri': 'Eridanus', 'Cnc': 'Cancer',
        'UMa': 'Ursa Major', 'Gru': 'Grus', 'Crt': 'Crater', 'Ori': 'Orion',
        'CrB': 'Corona Borealis', 'Psc': 'Pisces', 'Aql': 'Aquila', 'Ser': 'Serpens',
        'Phe': 'Phoenix', 'Lep': 'Lepus', 'Ari': 'Aries', 'Oph': 'Ophiuchus',
        'Her': 'Hercules', 'Cap': 'Capricornus', 'PsA': 'Piscis Austrinus',
        'CMi': 'Canis Minor', 'Equ': 'Equuleus', 'UMi': 'Ursa Minor', 'Tri': 'Triangulum',
        'Lib': 'Libra', 'Oct': 'Octans', 'LMi': 'Leo Minor', 'Sge': 'Sagitta', 'Lyr': 'Lyra'
    }
    
    return constellation_map.get(constellation_abbreviation, None)

def extract_messier_objects(file):
    df = pd.read_csv(file)
    
    df['friendlyName'] = pd.NA
    
    df['ngcId'] = pd.NA
    df['catalogId'] = 'M' + df['ObjectNum'].astype(str)
    
    df['ra'] = pd.NA
    df['dec'] = pd.NA
    
    # Iterate through the rows of the DataFrame
    for index, row in df.iterrows():
        ngc_id, friendly_name = extract_ngc_id(row['Name'])

        if (friendly_name == None):
            friendly_name = get_friendly_name(ngc_id)
            
        if (friendly_name == None):
            friendly_name = df.at[index, 'catalogId']
        
        df.at[index, 'friendlyName'] = friendly_name
        df.at[index, 'ngcId'] = ngc_id or pd.NA

        # RA and Dec collapse into coordinates column
        ra = (row['RAHour'] + row['RAMinute']/60) * 15
        df.at[index, 'ra'] = ra

        dec_sign = -1 if row['DecSign'].strip() == '-' else 1
        dec = dec_sign * (row['DecDeg'] + row['DecMinute']/60)
        df.at[index, 'dec'] = dec

    df['Magnitude'] = df['Magnitude'].apply(convert_magnitude) 
    df['defaultImage'] = df['Type'].apply(map_default_image)
        
    # Drop the original columns used to calculate RA and Dec
    df = df.drop(columns=['ObjectNum', 'Name', 'RAHour', 'RAMinute', 'DecSign', 'DecDeg', 'DecMinute', 'Info'])

    # Rename
    df.rename(columns={"Constellation": "constellation", "Magnitude": "magnitude", "Type": "desc"}, inplace=True)
    
    df['type'] = 'MESSIER'
    
    # Reorder
    column_order = ['friendlyName', 'ngcId', 'type', 'catalogId', 'ra', 'dec', 'desc', 'constellation', 'magnitude', 'defaultImage']
    df = df[column_order]
    
    return df

def extract_caldwell_objects(file):
    df = pd.read_csv(file)
    
    df['friendlyName'] = pd.NA

    df['ngcId'] = pd.NA
    df['catalogId'] = 'Caldwell ' + df['ObjectNum'].astype(str)
    
    df['ra'] = pd.NA
    df['dec'] = pd.NA
    
    # Iterate through the rows of the DataFrame
    for index, row in df.iterrows():
        ngc_id, friendly_name = extract_ngc_id(row['Name'])

        if (friendly_name == None):
            friendly_name = get_friendly_name(ngc_id)
        
        df.at[index, 'friendlyName'] = friendly_name or pd.NA
        df.at[index, 'ngcId'] = ngc_id or pd.NA

        if (friendly_name == None):
            friendly_name = ngc_id or df.at[index, 'catalogId']
        
        df.at[index, 'friendlyName'] = friendly_name
        df.at[index, 'ngcId'] = ngc_id or pd.NA

        # RA and Dec collapse into coordinates column
        ra = (row['RAHour'] + row['RAMinute']/60) * 15
        df.at[index, 'ra'] = ra

        dec_sign = -1 if row['DecSign'].strip() == '-' else 1
        dec = dec_sign * (row['DecDeg'] + row['DecMinute']/60)
        df.at[index, 'dec'] = dec  
        
    df['Constellation'] = df['Constellation'].apply(map_constellation)
    df['Magnitude'] = df['Magnitude'].apply(convert_magnitude)  
    df['defaultImage'] = df['Type'].apply(map_default_image)
    
    # Drop the original columns used to calculate RA and Dec
    df = df.drop(columns=['ObjectNum', 'Name', 'RAHour', 'RAMinute', 'DecSign', 'DecDeg', 'DecMinute', 'Info'])

    # Rename
    df.rename(columns={"Constellation": "constellation", "Magnitude": "magnitude", "Type": "desc"}, inplace=True)
    
    df['type'] = 'CALDWELL'
    
    # Reorder
    column_order = ['friendlyName', 'ngcId', 'type', 'catalogId', 'ra', 'dec', 'desc', 'constellation', 'magnitude', 'defaultImage']
    df = df[column_order]
    
    return df

def stars_convert_ra(ra_str):
    """Convert RA from hms format to decimal degrees."""
    # Extract hours, minutes, and seconds
    h, m, s = [float(i) for i in re.findall(r"\d+", ra_str)]
    # Convert to decimal degrees
    ra_deg = 15 * (h + m/60 + s/3600)
    return ra_deg

def stars_convert_dec(dec_str):
    """Convert Dec from °' format to decimal degrees."""
    # Handle the sign of the declination
    sign = -1 if "-" in dec_str else 1
    # Extract degrees and minutes
    deg, minute = [float(i) for i in re.findall(r"\d+", dec_str)]
    # Convert to decimal degrees
    dec_deg = sign * (deg + minute/60)
    return dec_deg

def extract_stars(file):
    df = pd.read_csv(file)
    
    df['ngcId'] = pd.NA
    df['catalogId'] = pd.NA
    
    df['type'] = 'STAR'
    df['desc'] = "Star"
    df['defaultImage'] = "star"
    df['ngcId'] = pd.NA
    
    df['Mag'] = df['Mag'].apply(convert_magnitude)
    df['Const'] = df['Const'].apply(map_constellation)
    
    df.rename(columns={"Name": "friendlyName", "RA": "ra", "Dec": "dec", "Const": "constellation", "Mag": "magnitude"}, inplace=True)

    df['ra'] = df['ra'].apply(stars_convert_ra)
    df['dec'] = df['dec'].apply(stars_convert_dec)
    
    # Reorder
    column_order = ['friendlyName', 'ngcId', 'type', 'catalogId', 'ra', 'dec', 'desc', 'constellation', 'magnitude', 'defaultImage']
    df = df[column_order]
   
    return df

In [3]:
file = "MessierObjects.csv"
df_messier = extract_messier_objects(file)
df_messier[0:200]

,friendlyName,ngcId,type,catalogId,ra,dec,desc,constellation,magnitude,defaultImage
0,Crab Nebula,NGC 1952,MESSIER,M1,83.625,22.016667,Supernova Remnant,Taurus,8.4,nebula
1,M2,NGC 7089,MESSIER,M2,323.375,-0.816667,Globular Cluster,Aquarius,6.5,cluster
2,M3,NGC 5272,MESSIER,M3,205.55,28.383333,Globular Cluster,Canes Venatici,6.2,cluster
3,M4,NGC 6121,MESSIER,M4,245.9,-26.533333,Globular Cluster,Scorpius,5.6,cluster
4,M5,NGC 5904,MESSIER,M5,229.65,2.083333,Globular Cluster,Serpens Caput,5.6,cluster
5,Butterfly Cluster,NGC 6405,MESSIER,M6,265.025,-32.216667,Open Cluster,Scorpius,5.3,cluster
6,Ptolemy¹s Cluster,NGC 6475,MESSIER,M7,268.475,-34.816667,Open Cluster,Scorpius,4.1,cluster
7,Lagoon Nebula,NGC 6523,MESSIER,M8,270.95,-24.383333,Diffuse Nebula,Sagittarius,6.0,nebula
8,M9,NGC 6333,MESSIER,M9,259.8,-18.516667,Globular Cluster,Ophiucus,7.7,cluster
9,M10,NGC 6254,MESSIER,M10,254.275,-4.1,Globular Cluster,Ophiucus,6.6,cluster
10,Wild Duck Cluster,NGC 6705,MESSIER,M11,282.775,-6.266667,Open Cluster,Scutum,6.3,cluster
11,M12,NGC 6218,MESSIER,M12,251.8,-1.95,Globular Cluster,Ophiucus,6.7,cluster
12,Hercules Globular Cluster,NGC 6205,MESSIER,M13,250.425,36.466667,Globular Cluster,Hercules,5.8,cluster
13,M14,NGC 6402,MESSIER,M14,264.4,-3.25,Globular Cluster,Ophiucus,7.6,cluster
14,M15,NGC 7078,MESSIER,M15,322.5,12.166667,Globular Cluster,Pegasus,6.2,cluster
15,Eagle Nebula Cluster,NGC 6611,MESSIER,M16,274.7,-13.783333,Open Cluster,Serpens Claudia,6.4,cluster
16,"Omega, Swan, Horseshoe Nebula",NGC 6618,MESSIER,M17,275.2,-16.183333,Diffuse Nebula,Sagittarius,7.0,nebula
17,M18,NGC 6613,MESSIER,M18,274.975,-17.133333,Open Cluster,Sagittarius,7.5,cluster
18,M19,NGC 6273,MESSIER,M19,255.65,-26.266667,Globular Cluster,Ophiucus,6.8,cluster
19,Trifid Nebula,NGC 6514,MESSIER,M20,270.575,-23.033333,Diffuse Nebula,Sagittarius,9.0,nebula
20,M21,NGC 6531,MESSIER,M21,271.15,-22.5,Open Cluster,Sagittarius,6.5,cluster
21,M22,NGC 6656,MESSIER,M22,279.1,-23.9,Globular Cluster,Sagittarius,5.1,cluster
22,M23,NGC 6494,MESSIER,M23,269.2,-19.016667,Open Cluster,Sagittarius,6.9,cluster
23,Milky Way Patch,NGC 6603,MESSIER,M24,274.6,-18.416667,Star Cloud,Sagittarius,4.6,star
24,IC 4725,<NA>,MESSIER,M25,277.925,-19.233333,Open Cluster,Sagittarius,6.5,cluster
25,M26,NGC 6694,MESSIER,M26,281.3,-9.4,Open Cluster,Scutum,8.0,cluster
26,Dumbbell Nebula,NGC 6853,MESSIER,M27,299.9,22.716667,Planetary Nebula,Vulpecula,7.4,nebula
27,M28,NGC 6626,MESSIER,M28,276.125,-24.866667,Globular Cluster,Sagittarius,6.8,cluster
28,M29,NGC 6913,MESSIER,M29,305.975,38.533333,Open Cluster,Cygnus,7.1,cluster
29,M30,NGC 7099,MESSIER,M30,325.1,-23.183333,Globular Cluster,Capricornus,7.2,cluster
30,Andromeda Galaxy,NGC 224,MESSIER,M31,10.675,41.266667,Spiral Galaxy,Andromeda,3.4,galaxy
31,Satellite of M31,NGC 221,MESSIER,M32,10.675,40.866667,Elliptical Galaxy,Andromeda,8.1,galaxy
32,Triangulum/Pinwheel Galaxy,NGC 598,MESSIER,M33,23.475,30.65,Spiral Galaxy,Triangulum,5.7,galaxy
33,M34,NGC 1039,MESSIER,M34,40.5,42.783333,Open Cluster,Perseus,5.5,cluster
34,M35,NGC 2168,MESSIER,M35,92.225,24.333333,Open Cluster,Gemini,5.3,cluster
35,M36,NGC 1960,MESSIER,M36,84.025,34.133333,Open Cluster,Auriga,6.3,cluster
36,M37,NGC 2099,MESSIER,M37,88.1,32.55,Open Cluster,Auriga,6.2,cluster
37,M38,NGC 1912,MESSIER,M38,82.175,35.833333,Open Cluster,Auriga,7.4,cluster
38,M39,NGC 7092,MESSIER,M39,323.05,48.433333,Open Cluster,Cygnus,5.2,cluster
39,Winecke 4,<NA>,MESSIER,M40,185.55,58.083333,Double Star,Ursa Major,<NA>,star
40,M41,NGC 2287,MESSIER,M41,101.75,-20.733333,Open Cluster,Canis Major,4.6,cluster
41,Great Orion Nebula,NGC 1976,MESSIER,M42,83.85,-5.45,Diffuse Nebula,Orion,4.0,nebula
42,de Mairan¹s Nebula,NGC 1982,MESSIER,M43,83.9,-5.266667,Diffuse Nebula,Orion,9.0,nebula
43,Beehive Cluster (Praesepe),NGC 2632,MESSIER,M44,130.025,19.983333,Open Cluster,Cancer,3.7,cluster
44,"Pleiades, Subaru, Seven Sisters",<NA>,MESSIER,M45,56.75,24.12,Open Cluster,Taurus,1.6,cluster
45,M46,NGC 2437,MESSIER,M46,115.45,-14.816667,Open Cluster,Puppis,6.0,cluster
46,M47,NGC 2422,MESSIER,M47,114.15,-14.5,Open Cluster,Puppis,5.2,cluster
47,M48,NGC 2548,MESSIER,M48,123.45,-5.8,Open Cluster,Hydra,5.5,cluster
48,M49,NGC 4472,MESSIER,M49,187.45,8.0,Elliptical Galaxy,Virgo,8.4,galaxy
49,M50,NGC 2323,MESSIER,M50,105.8,-8.333333,Open Cluster,Monocerus,6.3,cluster
50,Whirlpool Galaxy,NGC 5194,MESSIER,M51,202.475,47.2,Spiral Galaxy,Canes Venatici,8.4,galaxy
51,M52,NGC 7654,MESSIER,M52,351.05,61.583333,Open Cluster,Cassiopeia,7.3,cluster
52,M53,NGC 5024,MESSIER,M53,198.225,18.166667,Globular Cluster,Coma Berenices,7.6,cluster
53,M54,NGC 6715,MESSIER,M54,283.775,-30.483333,Globular Cluster,Sagittarius,7.6,cluster
54,M55,NGC 6809,MESSIER,M55,295.0,-30.966667,Globular Cluster,Sagittarius,6.3,cluster
55,M56,NGC 6779,MESSIER,M56,289.15,30.183333,Globular Cluster,Lyra,8.3,cluster
56,Ring Nebula,NGC 6720,MESSIER,M57,283.4,33.033333,Planetary Nebula,Lyra,8.8,nebula
57,M58,NGC 4579,MESSIER,M58,189.425,11.816667,Spiral Galaxy,Virgo,9.7,galaxy
58,M59,NGC 4621,MESSIER,M59,190.5,11.65,Elliptical Galaxy,Virgo,9.6,galaxy
59,M60,NGC 4649,MESSIER,M60,190.925,11.55,Elliptical Galaxy,Virgo,8.8,galaxy
60,M61,NGC 4303,MESSIER,M61,185.475,4.466667,Spiral Galaxy,Virgo,9.7,galaxy
61,M62,NGC 6266,MESSIER,M62,255.3,-30.116667,Globular Cluster,Ophiucus,6.5,cluster
62,Sunflower Galaxy,NGC 5055,MESSIER,M63,198.95,42.033333,Spiral Galaxy,Canes Venatici,8.6,galaxy
63,Blackeye Galaxy,NGC 4826,MESSIER,M64,194.175,21.683333,Spiral Galaxy,Coma Berenices,8.5,galaxy
64,M65,NGC 3623,MESSIER,M65,169.725,13.083333,Spiral Galaxy,Leo,9.3,galaxy
65,M66,NGC 3627,MESSIER,M66,170.05,12.983333,Spiral Galaxy,Leo,8.9,galaxy
66,M67,NGC 2682,MESSIER,M67,132.6,11.816667,Open Cluster,Cancer,6.1,cluster
67,M68,NGC 4590,MESSIER,M68,189.875,-26.75,Globular Cluster,Hydra,7.8,cluster
68,M69,NGC 6637,MESSIER,M69,277.85,-32.35,Globular Cluster,Sagittarius,7.6,cluster
69,M70,NGC 6681,MESSIER,M70,280.8,-32.3,Globular Cluster,Sagittarius,7.9,cluster
70,M71,NGC 6838,MESSIER,M71,298.45,18.783333,Globular Cluster,Sagitta,8.3,cluster
71,M72,NGC 6981,MESSIER,M72,313.375,-12.533333,Globular Cluster,Aquarius,9.3,cluster
72,Group of 4 stars,NGC 6994,MESSIER,M73,314.75,-12.633333,Group/Asterism,Aquarius,9.0,star
73,M74,NGC 628,MESSIER,M74,24.175,15.783333,Spiral Galaxy,Pisces,9.4,galaxy
74,M75,NGC 6864,MESSIER,M75,301.525,-21.916667,Globular Cluster,Sagittarius,8.5,cluster
75,"Little Dumbell, Cork, Butterfly Nebula",NGC 650,MESSIER,M76,25.575,51.566667,Planetary Nebula,Perseus,10.1,nebula
76,Cetus A,NGC 1068,MESSIER,M77,40.675,0.016667,Spiral Galaxy,Cetus,8.9,galaxy
77,M78,NGC 2068,MESSIER,M78,86.675,0.05,Diffuse Nebula,Orion,8.3,nebula
78,M79,NGC 1904,MESSIER,M79,81.125,-24.55,Globular Cluster,Lepus,7.7,cluster
79,M80,NGC 6093,MESSIER,M80,244.25,-22.983333,Globular Cluster,Scorpius,7.3,cluster
80,Bode¹s Galaxy,NGC 3031,MESSIER,M81,148.9,69.066667,Spiral Galaxy,Ursa Major,6.9,galaxy
81,Cigar Galaxy,NGC 3034,MESSIER,M82,148.95,69.683333,Irregular Galaxy,Ursa Major,8.4,galaxy
82,Southern Pinwheel Galaxy,NGC 5236,MESSIER,M83,204.25,-29.866667,Spiral Galaxy,Hydra,7.6,galaxy
83,M84,NGC 4374,MESSIER,M84,186.275,12.883333,Lenticular (S0) Galaxy,Virgo,9.1,galaxy
84,M85,NGC 4382,MESSIER,M85,186.35,18.183333,Lenticular (S0) Galaxy,Coma Berenices,9.1,galaxy
85,FAUST V051,NGC 4406,MESSIER,M86,186.55,12.95,Lenticular (S0) Galaxy,Virgo,8.9,galaxy
86,Virgo A,NGC 4486,MESSIER,M87,187.7,12.4,Elliptical Galaxy,Virgo,8.6,galaxy
87,M88,NGC 4501,MESSIER,M88,188.0,14.416667,Spiral Galaxy,Coma Berenices,9.6,galaxy
88,M89,NGC 4552,MESSIER,M89,188.925,12.55,Elliptical Galaxy,Virgo,9.8,galaxy
89,M90,NGC 4569,MESSIER,M90,189.2,13.166667,Spiral Galaxy,Virgo,9.5,galaxy
90,M91,NGC 4548,MESSIER,M91,188.85,14.5,Spiral Galaxy,Coma Berenices,10.2,galaxy
91,M92,NGC 6341,MESSIER,M92,259.275,43.133333,Globular Cluster,Hercules,6.4,cluster
92,M93,NGC 2447,MESSIER,M93,116.15,-23.866667,Open Cluster,Puppis,6.0,cluster
93,M94,NGC 4736,MESSIER,M94,192.725,41.116667,Spiral Galaxy,Canes Venatici,8.2,galaxy
94,M95,NGC 3351,MESSIER,M95,161.0,11.7,Spiral Galaxy,Leo,9.7,galaxy
95,M96,NGC 3368,MESSIER,M96,161.7,11.816667,Spiral Galaxy,Leo,9.2,galaxy
96,Owl Nebula,NGC 3587,MESSIER,M97,168.7,55.016667,Planetary Nebula,Ursa Major,9.9,nebula
97,M98,NGC 4192,MESSIER,M98,183.45,14.9,Spiral Galaxy,Coma Berenices,10.1,galaxy
98,Virgo Cluster Pinwheel,NGC 4254,MESSIER,M99,184.7,14.416667,Spiral Galaxy,Coma Berenices,9.9,galaxy
99,M100,NGC 4321,MESSIER,M100,185.725,15.816667,Spiral Galaxy,Coma Berenices,9.3,galaxy
100,Pinwheel Galaxy,NGC 5457,MESSIER,M101,210.8,54.35,Spiral Galaxy,Ursa Major,7.9,galaxy
101,Spindle Galaxy,NGC 5866,MESSIER,M102,226.625,55.766667,Lenticular (S0) Galaxy,Draco,9.9,galaxy
102,M103,NGC 581,MESSIER,M103,23.3,60.7,Open Cluster,Cassiopeia,7.4,cluster
103,Sombrero Galaxy,NGC 4594,MESSIER,M104,190.0,-11.616667,Spiral Galaxy,Virgo,8.0,galaxy
104,M105,NGC 3379,MESSIER,M105,161.95,12.583333,Elliptical Galaxy,Leo,9.3,galaxy
105,M106,NGC 4258,MESSIER,M106,184.75,47.3,Spiral Galaxy,Canes Venatici,8.4,galaxy
106,M107,NGC 6171,MESSIER,M107,248.125,-13.05,Globular Cluster,Ophiucus,7.9,cluster
107,M108,NGC 3556,MESSIER,M108,167.875,55.666667,Spiral Galaxy,Ursa Major,10.0,galaxy
108,M109,NGC 3992,MESSIER,M109,179.4,53.383333,Spiral Galaxy,Ursa Major,9.8,galaxy
109,Satellite of M31,NGC 205,MESSIER,M110,10.1,41.683333,Elliptical Galaxy,Andromeda,8.5,galaxy

In [4]:
file = "CaldwellObjects.csv"
df_caldwell = extract_caldwell_objects(file)


# Provide some friendly names not provided by Simbad
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 2", "friendlyName"] = "Bow-Tie Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 5", "friendlyName"] = "Hidden Galaxy"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 6", "friendlyName"] = "Cat's Eye Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 9", "friendlyName"] = "Cave Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 12", "friendlyName"] = "Fireworks Galaxy"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 14", "friendlyName"] = "Double Cluster (h&X Persei)"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 19", "friendlyName"] = "Cocoon Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 23", "friendlyName"] = "Silver Sliver Galaxy"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 31", "friendlyName"] = "Flaming Star Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 33", "friendlyName"] = "East Veil"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 34", "friendlyName"] = "West Veil"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 35", "friendlyName"] = "Coma B"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 38", "friendlyName"] = "Needle Galaxy"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 39", "friendlyName"] = "Eskimo/Clown Face Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 41", "friendlyName"] = "Hyades Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 46", "friendlyName"] = "Hubble's Variable Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 49", "friendlyName"] = "Rosette Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 50", "friendlyName"] = "Satellite Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 56", "friendlyName"] = "Skull Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 60", "friendlyName"] = "Antennae Galaxies"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 61", "friendlyName"] = "Antennae Galaxies" # same as C60
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 68", "friendlyName"] = "R CrA Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 80", "friendlyName"] = "Omega Centauri"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 85", "friendlyName"] = "Omicron Velorum Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 89", "friendlyName"] = "S Normae Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 91", "friendlyName"] = "Wishing Well Culster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 92", "friendlyName"] = "Eta Carinae Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 93", "friendlyName"] = "Great Peacock Globular"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 96", "friendlyName"] = "Southern Beehive Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 97", "friendlyName"] = "Pearl Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 99", "friendlyName"] = "Coalsack Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 100", "friendlyName"] = "Lambda Centauri Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 102", "friendlyName"] = "Theta Car Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 103", "friendlyName"] = "Tarantula Nebula"

#df_caldwell[['catalogId', 'friendlyName', 'desc']]

df_caldwell[0:200]

,friendlyName,ngcId,type,catalogId,ra,dec,desc,constellation,magnitude,defaultImage
0,NGC 188,NGC 188,CALDWELL,Caldwell 1,11.1,85.333333,Open Cluster,Cepheus,8.1,cluster
1,Bow-Tie Nebula,NGC 40,CALDWELL,Caldwell 2,3.25,72.533333,Planetary Nebula,Cepheus,12.4,nebula
2,NGC 4236,NGC 4236,CALDWELL,Caldwell 3,184.175,69.466667,Spiral Galaxy,Draco,9.7,galaxy
3,IRIS Nebula,NGC 7023,CALDWELL,Caldwell 4,315.45,68.2,Bright Nebula,Cepheus,<NA>,nebula
4,Hidden Galaxy,<NA>,CALDWELL,Caldwell 5,56.7,68.1,Spiral Galaxy,Camelopardalis,9.2,galaxy
5,Cat's Eye Nebula,NGC 6543,CALDWELL,Caldwell 6,269.65,66.633333,Planetary Nebula,Draco,8.1,nebula
6,NGC 2403,NGC 2403,CALDWELL,Caldwell 7,114.225,65.6,Spiral Galaxy,Camelopardalis,8.4,galaxy
7,NGC 559,NGC 559,CALDWELL,Caldwell 8,22.375,63.3,Open Cluster,Cassiopeia,9.5,cluster
8,Cave Nebula,<NA>,CALDWELL,Caldwell 9,344.2,62.616667,Bright Nebula,Cepheus,<NA>,nebula
9,NGC 663,NGC 663,CALDWELL,Caldwell 10,26.5,61.25,Open Cluster,Cassiopeia,7.1,cluster
10,Bubble Nebula,NGC 7635,CALDWELL,Caldwell 11,350.175,61.2,Bright Nebula,Cassiopeia,<NA>,nebula
11,Fireworks Galaxy,NGC 6946,CALDWELL,Caldwell 12,308.7,60.15,Spiral Galaxy,Cepheus,8.9,galaxy
12,Owl Cluster,NGC 457,CALDWELL,Caldwell 13,19.775,58.333333,Open Cluster,Cassiopeia,6.4,cluster
13,Double Cluster (h&X Persei),NGC 869,CALDWELL,Caldwell 14,35.0,57.133333,Open Cluster,Perseus,4.3,cluster
14,Blinking Planetary,NGC 6826,CALDWELL,Caldwell 15,296.2,50.516667,Planetary Nebula,Cygnus,8.8,nebula
15,NGC 7243,NGC 7243,CALDWELL,Caldwell 16,333.825,49.883333,Open Cluster,Lacerta,6.4,cluster
16,NGC 147,NGC 147,CALDWELL,Caldwell 17,8.3,48.5,Elliptical Galaxy,Cassiopeia,9.3,galaxy
17,NGC 185,NGC 185,CALDWELL,Caldwell 18,9.75,48.333333,Elliptical Galaxy,Cassiopeia,9.2,galaxy
18,Cocoon Nebula,<NA>,CALDWELL,Caldwell 19,328.375,47.266667,Bright Nebula,Cygnus,<NA>,nebula
19,North America Nebula,NGC 7000,CALDWELL,Caldwell 20,314.7,44.333333,Bright Nebula,Cygnus,<NA>,nebula
20,NGC 4449,NGC 4449,CALDWELL,Caldwell 21,187.05,44.1,Irregular Galaxy,Canes Venatici,9.4,galaxy
21,Copeland's Blue Snowball,NGC 7662,CALDWELL,Caldwell 22,351.475,42.55,Planetary Nebula,Andromeda,8.3,nebula
22,Silver Sliver Galaxy,NGC 891,CALDWELL,Caldwell 23,35.65,42.35,Spiral Galaxy,Andromeda,9.9,galaxy
23,Perseus A,NGC 1275,CALDWELL,Caldwell 24,49.95,41.516667,Irregular Galaxy,Perseus,11.6,galaxy
24,NGC 2419,NGC 2419,CALDWELL,Caldwell 25,114.525,38.883333,Globular Cluster,Lynx,10.4,cluster
25,NGC 4244,NGC 4244,CALDWELL,Caldwell 26,184.375,37.816667,Spiral Galaxy,Canes Venatici,10.2,galaxy
26,Crescent Nebula,NGC 6888,CALDWELL,Caldwell 27,303.0,38.35,Bright Nebula,Cygnus,<NA>,nebula
27,NGC 752,NGC 752,CALDWELL,Caldwell 28,29.45,37.683333,Open Cluster,Andromeda,5.7,cluster
28,NGC 5005,NGC 5005,CALDWELL,Caldwell 29,197.725,37.05,Spiral Galaxy,Canes Venatici,9.8,galaxy
29,NGC 7331,NGC 7331,CALDWELL,Caldwell 30,339.275,34.416667,Spiral Galaxy,Pegasus,9.5,galaxy
30,Flaming Star Nebula,<NA>,CALDWELL,Caldwell 31,79.05,34.266667,Bright Nebula,Auriga,<NA>,nebula
31,Whale Galaxy,NGC 4631,CALDWELL,Caldwell 32,190.525,32.533333,Spiral Galaxy,Canes Venatici,9.3,galaxy
32,East Veil,NGC 6992,CALDWELL,Caldwell 33,314.1,31.716667,Supernova Remnant,Cygnus,<NA>,nebula
33,West Veil,NGC 6960,CALDWELL,Caldwell 34,311.425,30.716667,Supernova Remnant,Cygnus,<NA>,nebula
34,Coma B,NGC 4889,CALDWELL,Caldwell 35,195.025,27.983333,Elliptical Galaxy,Coma Berenices,11.4,galaxy
35,NGC 4559,NGC 4559,CALDWELL,Caldwell 36,189.0,27.966667,Spiral Galaxy,Coma Berenices,9.8,galaxy
36,NGC 6885,NGC 6885,CALDWELL,Caldwell 37,303.0,26.483333,Open Cluster,Vulpecula,5.9,cluster
37,Needle Galaxy,NGC 4565,CALDWELL,Caldwell 38,189.075,25.983333,Spiral Galaxy,Coma Berenices,9.6,galaxy
38,Eskimo/Clown Face Nebula,NGC 2392,CALDWELL,Caldwell 39,112.3,20.916667,Planetary Nebula,Gemini,9.2,nebula
39,NGC 3626,NGC 3626,CALDWELL,Caldwell 40,170.025,18.35,Spiral Galaxy,Leo,10.9,galaxy
40,Hyades Cluster,<NA>,CALDWELL,Caldwell 41,66.75,16.0,Open Cluster,Taurus,0.5,cluster
41,NGC 7006,NGC 7006,CALDWELL,Caldwell 42,315.375,16.183333,Globular Cluster,Delphinus,10.6,cluster
42,NGC 7814,NGC 7814,CALDWELL,Caldwell 43,0.825,16.15,Spiral Galaxy,Pegasus,10.5,galaxy
43,NGC 7479,NGC 7479,CALDWELL,Caldwell 44,346.225,12.316667,Spiral Galaxy,Pegasus,11.0,galaxy
44,NGC 5248,NGC 5248,CALDWELL,Caldwell 45,204.375,8.883333,Spiral Galaxy,Boötes,10.2,galaxy
45,Hubble's Variable Nebula,NGC 2261,CALDWELL,Caldwell 46,99.8,8.733333,Bright Nebula,Monoceros,<NA>,nebula
46,NGC 6934,NGC 6934,CALDWELL,Caldwell 47,308.55,7.4,Globular Cluster,Delphinus,8.9,cluster
47,NGC 2775,NGC 2775,CALDWELL,Caldwell 48,137.575,7.033333,Spiral Galaxy,Canes Major,10.3,galaxy
48,Rosette Nebula,NGC 2237,CALDWELL,Caldwell 49,98.075,5.05,Bright Nebula,Monoceros,<NA>,nebula
49,Satellite Cluster,NGC 2244,CALDWELL,Caldwell 50,98.1,4.866667,Open Cluster,Monoceros,4.8,cluster
50,IC 1613,<NA>,CALDWELL,Caldwell 51,16.2,2.116667,Irregular Galaxy,Cetus,9.3,galaxy
51,NGC 4697,NGC 4697,CALDWELL,Caldwell 52,192.15,-5.8,Elliptical Galaxy,Virgo,9.3,galaxy
52,Spindle Galaxy,NGC 3115,CALDWELL,Caldwell 53,151.3,-7.716667,Elliptical Galaxy,Sextans,9.1,galaxy
53,NGC 2506,NGC 2506,CALDWELL,Caldwell 54,120.05,-10.783333,Open Cluster,Monoceros,7.6,cluster
54,Saturn Nebula,NGC 7009,CALDWELL,Caldwell 55,316.05,-11.366667,Planetary Nebula,Aquarius,8.0,nebula
55,Skull Nebula,NGC 246,CALDWELL,Caldwell 56,11.75,-11.883333,Planetary Nebula,Cetus,10.9,nebula
56,Barnard's Galaxy,NGC 6822,CALDWELL,Caldwell 57,296.225,-14.8,Irregular Galaxy,Sagittarius,8.8,galaxy
57,Caroline's Cluster,NGC 2360,CALDWELL,Caldwell 58,109.45,-15.616667,Open Cluster,Canis Major,7.2,cluster
58,Jupiter's Ghost Nebula,NGC 3242,CALDWELL,Caldwell 59,156.2,-18.633333,Planetary Nebula,Hydra,7.8,nebula
59,Antennae Galaxies,NGC 4038,CALDWELL,Caldwell 60,180.475,-18.866667,Spiral Galaxy,Corvus,10.7,galaxy
60,Antennae Galaxies,NGC 4039,CALDWELL,Caldwell 61,180.475,-18.883333,Spiral Galaxy,Corvus,10.7,galaxy
61,NGC 247,NGC 247,CALDWELL,Caldwell 62,11.775,-20.766667,Spiral Galaxy,Cetus,9.1,galaxy
62,Helix Nebula,NGC 7293,CALDWELL,Caldwell 63,337.4,-20.8,Planetary Nebula,Aquarius,7.3,nebula
63,Tau CMa,NGC 2362,CALDWELL,Caldwell 64,109.7,-24.95,Open Cluster,Canis Major,4.1,cluster
64,Sculptor Filament,NGC 253,CALDWELL,Caldwell 65,11.9,-25.283333,Spiral Galaxy,Sculptor,7.1,galaxy
65,NGC 5694,NGC 5694,CALDWELL,Caldwell 66,219.9,-26.533333,Globular Cluster,Hydra,10.2,cluster
66,NGC 1097,NGC 1097,CALDWELL,Caldwell 67,41.575,-30.283333,Spiral Galaxy,Fornax,9.2,galaxy
67,R CrA Nebula,NGC 6729,CALDWELL,Caldwell 68,285.475,-36.95,Bright Nebula,Corona Australis,<NA>,nebula
68,Bug Nebula,NGC 6302,CALDWELL,Caldwell 69,258.425,-37.1,Planetary Nebula,Scorpius,9.6,nebula
69,NGC 300,NGC 300,CALDWELL,Caldwell 70,13.725,-37.683333,Spiral Galaxy,Sculptor,8.7,galaxy
70,NGC 2477,NGC 2477,CALDWELL,Caldwell 71,118.075,-38.55,Open Cluster,Puppis,5.8,cluster
71,NGC 55,NGC 55,CALDWELL,Caldwell 72,3.725,-39.183333,Spiral Galaxy,Sculptor,7.9,galaxy
72,NGC 1851,NGC 1851,CALDWELL,Caldwell 73,78.525,-40.05,Globular Cluster,Columba,7.3,cluster
73,Eight-Burst Nebula,NGC 3132,CALDWELL,Caldwell 74,151.925,-40.433333,Planetary Nebula,Vela,9.4,nebula
74,NGC 6124,NGC 6124,CALDWELL,Caldwell 75,246.4,-40.666667,Open Cluster,Scorpius,5.8,cluster
75,NGC 6231,NGC 6231,CALDWELL,Caldwell 76,253.5,-41.8,Open Cluster,Scorpius,2.6,cluster
76,Centaurus A,NGC 5128,CALDWELL,Caldwell 77,201.375,-43.016667,Elliptical Galaxy,Centaurus,7.0,galaxy
77,NGC 6541,NGC 6541,CALDWELL,Caldwell 78,272.0,-43.7,Globular Cluster,Corona Australis,6.6,cluster
78,NGC 3201,NGC 3201,CALDWELL,Caldwell 79,154.4,-46.416667,Globular Cluster,Vela,6.7,cluster
79,Omega Centauri,NGC 5139,CALDWELL,Caldwell 80,201.7,-47.483333,Globular Cluster,Centaurus,3.6,cluster
80,NGC 6352,NGC 6352,CALDWELL,Caldwell 81,261.375,-48.416667,Globular Cluster,Ara,8.1,cluster
81,NGC 6193,NGC 6193,CALDWELL,Caldwell 82,250.325,-48.766667,Open Cluster,Ara,5.2,cluster
82,NGC 4945,NGC 4945,CALDWELL,Caldwell 83,196.35,-49.466667,Spiral Galaxy,Centaurus,8.7,galaxy
83,NGC 5286,NGC 5286,CALDWELL,Caldwell 84,206.6,-51.366667,Globular Cluster,Centaurus,7.6,cluster
84,Omicron Velorum Cluster,<NA>,CALDWELL,Caldwell 85,130.05,-53.066667,Open Cluster,Vela,2.5,cluster
85,NGC 6397,NGC 6397,CALDWELL,Caldwell 86,265.175,-53.666667,Globular Cluster,Ara,5.6,cluster
86,NGC 1261,NGC 1261,CALDWELL,Caldwell 87,48.075,-55.216667,Globular Cluster,Horologium,8.4,cluster
87,NGC 5823,NGC 5823,CALDWELL,Caldwell 88,226.425,-55.6,Open Cluster,Circinus,7.9,cluster
88,S Normae Cluster,NGC 6087,CALDWELL,Caldwell 89,244.725,-57.9,Open Cluster,Norma,5.4,cluster
89,NGC 2867,NGC 2867,CALDWELL,Caldwell 90,140.35,-58.316667,Planetary Nebula,Carina,<NA>,nebula
90,Wishing Well Culster,NGC 3532,CALDWELL,Caldwell 91,166.6,-58.666667,Open Cluster,Carina,3.0,cluster
91,Eta Carinae Nebula,NGC 3372,CALDWELL,Caldwell 92,160.95,-59.866667,Bright Nebula,Carina,<NA>,nebula
92,Great Peacock Globular,NGC 6752,CALDWELL,Caldwell 93,287.725,-59.983333,Globular Cluster,Pavo,5.4,cluster
93,Herschel's Jewel Box,NGC 4755,CALDWELL,Caldwell 94,193.4,-60.333333,Open Cluster,Crux,4.2,cluster
94,NGC 6025,NGC 6025,CALDWELL,Caldwell 95,240.925,-60.5,Open Cluster,Triangulum Australe,5.1,cluster
95,Southern Beehive Cluster,NGC 2516,CALDWELL,Caldwell 96,119.575,-60.866667,Open Cluster,Carina,3.8,cluster
96,Pearl Cluster,NGC 3766,CALDWELL,Caldwell 97,174.025,-61.616667,Open Cluster,Centaurus,5.3,cluster
97,Coalsack Cluster,NGC 4609,CALDWELL,Caldwell 98,190.575,-62.966667,Open Cluster,Crux,6.9,cluster
98,Coalsack Nebula,<NA>,CALDWELL,Caldwell 99,193.25,-63.0,Dark Nebula,Crux,<NA>,nebula
99,Lambda Centauri Nebula,<NA>,CALDWELL,Caldwell 100,174.15,-63.033333,Open Cluster,Centaurus,4.5,cluster
100,NGC 6744,NGC 6744,CALDWELL,Caldwell 101,287.45,-63.85,Spiral Galaxy,Pavo,8.3,galaxy
101,Theta Car Cluster,<NA>,CALDWELL,Caldwell 102,160.8,-64.4,Open Cluster,Carina,1.9,cluster
102,Tarantula Nebula,NGC 2070,CALDWELL,Caldwell 103,84.675,-69.1,Bright Nebula,Dorado,<NA>,nebula
103,NGC 362,NGC 362,CALDWELL,Caldwell 104,15.8,-70.85,Globular Cluster,Tucana,6.6,cluster
104,NGC 4833,NGC 4833,CALDWELL,Caldwell 105,194.9,-70.883333,Globular Cluster,Musca,7.3,cluster
105,47 Tuc Cluster,NGC 104,CALDWELL,Caldwell 106,6.025,-72.083333,Globular Cluster,Tucana,4.0,cluster
106,NGC 6101,NGC 6101,CALDWELL,Caldwell 107,246.45,-72.2,Globular Cluster,Apus,9.3,cluster
107,NGC 4372,NGC 4372,CALDWELL,Caldwell 108,186.45,-72.666667,Globular Cluster,Musca,7.8,cluster
108,NGC 3195,NGC 3195,CALDWELL,Caldwell 109,152.375,-80.866667,Planetary Nebula,Chamaeleon,<NA>,nebula

In [5]:
file = "Alignment Stars.csv"
df_stars = extract_stars(file)
df_stars[0:5]

,friendlyName,ngcId,type,catalogId,ra,dec,desc,constellation,magnitude,defaultImage
0,Acamar,<NA>,STAR,<NA>,44.566667,-40.300000,Star,Eridanus,3.2,star
1,Achernar,<NA>,STAR,<NA>,24.429167,-57.233333,Star,Eridanus,0.5,star
2,Achird,<NA>,STAR,<NA>,12.275000,57.816667,Star,Cassiopeia,3.4,star
3,Acrux,<NA>,STAR,<NA>,186.650000,-63.100000,Star,Crux,1.3,star
4,Acubens,<NA>,STAR,<NA>,134.620833,11.850000,Star,Cancer,4.3,star

In [6]:
df_combined = pd.concat([df_messier, df_caldwell, df_stars], ignore_index=True)

df_combined['id'] = 0
df_combined['observationStatus'] = 'NOT_OBSERVED'

In [7]:
df_combined['defaultImage'].value_counts()

star       250
cluster    102
galaxy      75
nebula      39
Name: defaultImage, dtype: int64

In [8]:
# Set the observation status of a few well known goods
df_combined.loc[df_combined['catalogId'] == "M1", 'observationStatus'] = 'SUGGESTED'  # Crab Nebula
df_combined.loc[df_combined['catalogId'] == "M6", 'observationStatus'] = 'GREAT'  # Butterfly Cluster
df_combined.loc[df_combined['catalogId'] == "M7", 'observationStatus'] = 'GREAT'  # Ptolemy's Cluster
df_combined.loc[df_combined['catalogId'] == "M8", 'observationStatus'] = 'GREAT'  # Lagoon Nebula
df_combined.loc[df_combined['catalogId'] == "M11", 'observationStatus'] = 'GREAT'  # Wild Duck Cluster
df_combined.loc[df_combined['catalogId'] == "M13", 'observationStatus'] = 'GREAT'  # Hercules Globular Cluster
df_combined.loc[df_combined['catalogId'] == "M16", 'observationStatus'] = 'SUGGESTED'  # Eagle Nebula
df_combined.loc[df_combined['catalogId'] == "M17", 'observationStatus'] = 'SUGGESTED'  # The Omega or Swan Nebula
df_combined.loc[df_combined['catalogId'] == "M22", 'observationStatus'] = 'SUGGESTED'  # Sagittarius cluster
df_combined.loc[df_combined['catalogId'] == "M27", 'observationStatus'] = 'GREAT'  # Dumbell nebula
df_combined.loc[df_combined['catalogId'] == "M31", 'observationStatus'] = 'GREAT'  # Andromeda Galaxy
df_combined.loc[df_combined['catalogId'] == "M42", 'observationStatus'] = 'GREAT'  # Orion Nebula
df_combined.loc[df_combined['catalogId'] == "M45", 'observationStatus'] = 'GREAT'  # Pleaiades
df_combined.loc[df_combined['catalogId'] == "M51", 'observationStatus'] = 'SUGGESTED'  # Whirlpool Galaxy
df_combined.loc[df_combined['catalogId'] == "M57", 'observationStatus'] = 'SUGGESTED'  # The Ring Nebula
df_combined.loc[df_combined['catalogId'] == "M81", 'observationStatus'] = 'SUGGESTED'  # The Bode's Galaxy
df_combined.loc[df_combined['catalogId'] == "M82", 'observationStatus'] = 'SUGGESTED'  # The Cigar Galaxy
df_combined.loc[df_combined['catalogId'] == "Caldwell 14", 'observationStatus'] = 'GREAT'  # Double Cluster
df_combined.loc[df_combined['catalogId'] == "Caldwell 33", 'observationStatus'] = 'SUGGESTED'  # Eastern Veil
df_combined.loc[df_combined['catalogId'] == "Caldwell 34", 'observationStatus'] = 'SUGGESTED'  # Western Veil 
df_combined.loc[df_combined['catalogId'] == "Caldwell 49", 'observationStatus'] = 'SUGGESTED'  # Rosette Nebula
df_combined.loc[df_combined['catalogId'] == "Caldwell 64", 'observationStatus'] = 'SUGGESTED'  # Cat's Eye Nebula
df_combined.loc[df_combined['catalogId'] == "Caldwell 104", 'observationStatus'] = 'SUGGESTED'  # Sombrero Galaxy

In [9]:
df_combined.to_json('items.json', orient='records', lines=False)