In [1]:
import re

import pandas as pd
pd.set_option('display.max_rows', None)

from astroquery.simbad import Simbad

In [17]:
def extract_ngc_id(name):
    """
    Extract the NGC ID and friendly name from the given string.
    
    Parameters:
        name (str): The string from which to extract the NGC ID and friendly name.
        
    Returns:
        tuple: (ngc_id, friendly_name) where both are strings or None.
    """
    # Regex to extract NGC ID format, considering 'NGC ' followed by digits
    ngc_pattern = re.compile(r'(NGC \d+)(/[\d]+)?')
    ngc_match = ngc_pattern.search(name)
    
    # Extract NGC ID
    ngc_id = ngc_match.group(1) if ngc_match else None
    
    # Extract friendly name
    if ngc_id:
        friendly_name = name.replace(ngc_id, '').replace(ngc_match.group(2) if ngc_match.group(2) else '', '').strip() or None
    else:
        friendly_name = name.strip() or None
    
    return ngc_id, friendly_name

def get_friendly_name(ngc_id):
    friendly_name = None
    try:
        result_table = Simbad.query_objectids(ngc_id)
        if result_table is not None:
            names = [name[5:] for name in result_table['ID'] if name.startswith("NAME")]
            if names:
                friendly_name = max(names, key=len)

    except Exception as e:
        print(f"An error occurred while querying {ngc_id}: {str(e)}")
    return friendly_name

def convert_magnitude(value):
    try:
        return float(value)
    except (ValueError, TypeError):
        return pd.NA

# Map the types to the new categories
def map_to_type(obj_type):
    mapping = {
        'Star': 'STAR',
        'Spiral Galaxy': 'GALAXY',
        'Elliptical Galaxy': 'GALAXY',
        'Irregular Galaxy': 'GALAXY',
        'Lenticular (S0) Galaxy': 'GALAXY',
        'Open Cluster': 'OPEN_CLUSTER',
        'Globular Cluster': 'GLOBULAR_CLUSTER',
        'Planetary Nebula': 'PLANETARY_NEBULA',
        'Bright Nebula': 'BRIGHT_NEBULA',
        'Diffuse Nebula': 'NEBULA',
        'Dark Nebula': 'DARK_NEBULA',
        'Supernova Remnant': 'SUPERNOVA_REMNANT',
        'Star Cloud': 'ASTERISM',
        'Double Star': 'ASTERISM',
        'Group/Asterism': 'ASTERISM'
    }
    
    return mapping.get(obj_type, 'UNKNOWN')

def map_constellation(constellation_abbreviation):
    constellation_map = {
        'Cep': 'Cepheus', 'Dra': 'Draco', 'Cam': 'Camelopardalis', 'Cas': 'Cassiopeia',
        'Per': 'Perseus', 'Cyg': 'Cygnus', 'Lac': 'Lacerta', 'CVn': 'Canes Venatici',
        'And': 'Andromeda', 'Lyn': 'Lynx', 'Peg': 'Pegasus', 'Aur': 'Auriga',
        'Com': 'Coma Berenices', 'Vul': 'Vulpecula', 'Gem': 'Gemini', 'Leo': 'Leo',
        'Tau': 'Taurus', 'Del': 'Delphinus', 'Boo': 'Boötes', 'Mon': 'Monoceros',
        'Can': 'Canes Major', 'Cet': 'Cetus', 'Vir': 'Virgo', 'Sex': 'Sextans',
        'Aqr': 'Aquarius', 'Sgr': 'Sagittarius', 'CMa': 'Canis Major', 'Hya': 'Hydra',
        'Crv': 'Corvus', 'Scl': 'Sculptor', 'For': 'Fornax', 'CrA': 'Corona Australis',
        'Sco': 'Scorpius', 'Pup': 'Puppis', 'Col': 'Columba', 'Vel': 'Vela',
        'Cen': 'Centaurus', 'Ara': 'Ara', 'Hor': 'Horologium', 'Cir': 'Circinus',
        'Nor': 'Norma', 'Car': 'Carina', 'Pav': 'Pavo', 'Cru': 'Crux',
        'TrA': 'Triangulum Australe', 'Dor': 'Dorado', 'Tuc': 'Tucana', 'Mus': 'Musca',
        'Aps': 'Apus', 'Cha': 'Chamaeleon', 'Eri': 'Eridanus', 'Cnc': 'Cancer',
        'UMa': 'Ursa Major', 'Gru': 'Grus', 'Crt': 'Crater', 'Ori': 'Orion',
        'CrB': 'Corona Borealis', 'Psc': 'Pisces', 'Aql': 'Aquila', 'Ser': 'Serpens',
        'Phe': 'Phoenix', 'Lep': 'Lepus', 'Ari': 'Aries', 'Oph': 'Ophiuchus',
        'Her': 'Hercules', 'Cap': 'Capricornus', 'PsA': 'Piscis Austrinus',
        'CMi': 'Canis Minor', 'Equ': 'Equuleus', 'UMi': 'Ursa Minor', 'Tri': 'Triangulum',
        'Lib': 'Libra', 'Oct': 'Octans', 'LMi': 'Leo Minor', 'Sge': 'Sagitta', 'Lyr': 'Lyra'
    }
    
    return constellation_map.get(constellation_abbreviation, None)

def extract_messier_objects(file):
    df = pd.read_csv(file)
    
    df['friendlyName'] = pd.NA
    
    df['ngcId'] = pd.NA
    df['messierId'] = 'M' + df['ObjectNum'].astype(str)
    df['caldwellId'] = pd.NA
    
    df['ra'] = pd.NA
    df['dec'] = pd.NA
    
    # Iterate through the rows of the DataFrame
    for index, row in df.iterrows():
        ngc_id, friendly_name = extract_ngc_id(row['Name'])

        if (friendly_name == None):
            friendly_name = get_friendly_name(ngc_id)
            
        if (friendly_name == None):
            friendly_name = df.at[index, 'messierId']
        else:
            friendly_name = df.at[index, 'messierId'] + " - " + friendly_name
        
        df.at[index, 'friendlyName'] = friendly_name
        df.at[index, 'ngcId'] = ngc_id or pd.NA

        # RA and Dec collapse into coordinates column
        ra = (row['RAHour'] + row['RAMinute']/60) * 15
        df.at[index, 'ra'] = ra

        dec_sign = -1 if row['DecSign'].strip() == '-' else 1
        dec = dec_sign * (row['DecDeg'] + row['DecMinute']/60)
        df.at[index, 'dec'] = dec

    df['Magnitude'] = df['Magnitude'].apply(convert_magnitude)
    df['Type'] = df['Type'].apply(map_to_type)        
        
    # Drop the original columns used to calculate RA and Dec
    df = df.drop(columns=['ObjectNum', 'Name', 'RAHour', 'RAMinute', 'DecSign', 'DecDeg', 'DecMinute', 'Info'])

    # Rename
    df.rename(columns={"Constellation": "constellation", "Magnitude": "magnitude", "Type": "type"}, inplace=True)
    
    # Reorder
    column_order = ['friendlyName', 'ngcId', 'messierId', 'caldwellId', 'ra', 'dec', 'type', 'constellation', 'magnitude']
    df = df[column_order]
    
    return df

def extract_caldwell_objects(file):
    df = pd.read_csv(file)
    
    df['friendlyName'] = pd.NA
    
    df['ngcId'] = pd.NA
    df['messierId'] = pd.NA
    df['caldwellId'] = 'Caldwell ' + df['ObjectNum'].astype(str)
    
    df['ra'] = pd.NA
    df['dec'] = pd.NA
    
    # Iterate through the rows of the DataFrame
    for index, row in df.iterrows():
        ngc_id, friendly_name = extract_ngc_id(row['Name'])

        if (friendly_name == None):
            friendly_name = get_friendly_name(ngc_id)
        
        df.at[index, 'friendlyName'] = friendly_name or pd.NA
        df.at[index, 'ngcId'] = ngc_id or pd.NA

        if (friendly_name == None):
            friendly_name = df.at[index, 'caldwellId']
        else:
            friendly_name = friendly_name
        
        df.at[index, 'friendlyName'] = friendly_name
        df.at[index, 'ngcId'] = ngc_id or pd.NA

        # RA and Dec collapse into coordinates column
        ra = (row['RAHour'] + row['RAMinute']/60) * 15
        df.at[index, 'ra'] = ra

        dec_sign = -1 if row['DecSign'].strip() == '-' else 1
        dec = dec_sign * (row['DecDeg'] + row['DecMinute']/60)
        df.at[index, 'dec'] = dec  
        
    df['Constellation'] = df['Constellation'].apply(map_constellation)
    df['Magnitude'] = df['Magnitude'].apply(convert_magnitude)
    df['Type'] = df['Type'].apply(map_to_type)     
    
    
    # Drop the original columns used to calculate RA and Dec
    df = df.drop(columns=['ObjectNum', 'Name', 'RAHour', 'RAMinute', 'DecSign', 'DecDeg', 'DecMinute', 'Info'])

    # Rename
    df.rename(columns={"Constellation": "constellation", "Magnitude": "magnitude", "Type": "type"}, inplace=True)
    
    # Reorder
    column_order = ['friendlyName', 'ngcId', 'messierId', 'caldwellId', 'ra', 'dec', 'type', 'constellation', 'magnitude']
    df = df[column_order]
    
    return df

def stars_convert_ra(ra_str):
    """Convert RA from hms format to decimal degrees."""
    # Extract hours, minutes, and seconds
    h, m, s = [float(i) for i in re.findall(r"\d+", ra_str)]
    # Convert to decimal degrees
    ra_deg = 15 * (h + m/60 + s/3600)
    return ra_deg

def stars_convert_dec(dec_str):
    """Convert Dec from °' format to decimal degrees."""
    # Handle the sign of the declination
    sign = -1 if "-" in dec_str else 1
    # Extract degrees and minutes
    deg, minute = [float(i) for i in re.findall(r"\d+", dec_str)]
    # Convert to decimal degrees
    dec_deg = sign * (deg + minute/60)
    return dec_deg

def extract_stars(file):
    df = pd.read_csv(file)
    
    df['ngcId'] = pd.NA
    df['messierId'] = pd.NA
    df['caldwellId'] = pd.NA
    
    df['type'] = 'STAR'
    df['ngcId'] = pd.NA
    
    df['Mag'] = df['Mag'].apply(convert_magnitude)
    df['Const'] = df['Const'].apply(map_constellation)
    
    df.rename(columns={"Name": "friendlyName", "RA": "ra", "Dec": "dec", "Const": "constellation", "Mag": "magnitude"}, inplace=True)

    df['ra'] = df['ra'].apply(stars_convert_ra)
    df['dec'] = df['dec'].apply(stars_convert_dec)
    
    # Reorder
    column_order = ['friendlyName', 'ngcId', 'messierId', 'caldwellId', 'ra', 'dec', 'type', 'constellation', 'magnitude']
    df = df[column_order]
    
    return df

In [18]:
file = "Alignment Stars.csv"
df_stars = extract_stars(file)
df_stars[0:5]

,friendlyName,ngcId,messierId,caldwellId,ra,dec,type,constellation,magnitude
0,Acamar,<NA>,<NA>,<NA>,44.566667,-40.300000,STAR,Eridanus,3.2
1,Achernar,<NA>,<NA>,<NA>,24.429167,-57.233333,STAR,Eridanus,0.5
2,Achird,<NA>,<NA>,<NA>,12.275000,57.816667,STAR,Cassiopeia,3.4
3,Acrux,<NA>,<NA>,<NA>,186.650000,-63.100000,STAR,Crux,1.3
4,Acubens,<NA>,<NA>,<NA>,134.620833,11.850000,STAR,Cancer,4.3

In [16]:
file = "CaldwellObjects.csv"
df_caldwell = extract_caldwell_objects(file)
# override a few values
df_caldwell.loc[4, 'friendlyName'] = 'Hidden Galaxy'  # Caldwell 5
df_caldwell.loc[18, 'friendlyName'] = 'Cocoon Nebula' # Caldwell 19
df_caldwell.loc[30, 'friendlyName'] = 'Flaming Star Nebula' # Caldwell 31
df_caldwell.loc[40, 'friendlyName'] = 'Hyades Cluster' # Caldwell 41
df_caldwell.loc[48, 'friendlyName'] = 'Rosette Nebula' # Caldwell 49
df_caldwell.loc[50, 'friendlyName'] = 'Caldwell 51' # Caldwell 51
df_caldwell.loc[84, 'friendlyName'] = 'Omicron Velorum Cluster' # Caldwell 85
df_caldwell.loc[98, 'friendlyName'] = 'Coalsack Nebula' # Caldwell 99
df_caldwell.loc[99, 'friendlyName'] = 'Lambda Centauri Nebula' # Caldwell 100
df_caldwell.loc[101, 'friendlyName'] = 'Theta Car Cluster' # Caldwell 102

df_caldwell[0:5]

,friendlyName,ngcId,messierId,caldwellId,ra,dec,type,constellation,magnitude
0,Caldwell 1,NGC 188,<NA>,Caldwell 1,11.1,85.333333,OPEN_CLUSTER,Cepheus,8.1
1,Caldwell 2,NGC 40,<NA>,Caldwell 2,3.25,72.533333,PLANETARY_NEBULA,Cepheus,12.4
2,Caldwell 3,NGC 4236,<NA>,Caldwell 3,184.175,69.466667,GALAXY,Draco,9.7
3,IRIS Nebula,NGC 7023,<NA>,Caldwell 4,315.45,68.2,BRIGHT_NEBULA,Cepheus,<NA>
4,Hidden Galaxy,<NA>,<NA>,Caldwell 5,56.7,68.1,GALAXY,Camelopardalis,9.2

In [19]:
file = "MessierObjects.csv"
df_messier = extract_messier_objects(file)
df_messier[0:5]

,friendlyName,ngcId,messierId,caldwellId,ra,dec,type,constellation,magnitude
0,M1 - Crab Nebula,NGC 1952,M1,<NA>,83.625,22.016667,SUPERNOVA_REMNANT,Taurus,8.4
1,M2,NGC 7089,M2,<NA>,323.375,-0.816667,GLOBULAR_CLUSTER,Aquarius,6.5
2,M3,NGC 5272,M3,<NA>,205.55,28.383333,GLOBULAR_CLUSTER,Canes Venatici,6.2
3,M4,NGC 6121,M4,<NA>,245.9,-26.533333,GLOBULAR_CLUSTER,Scorpius,5.6
4,M5,NGC 5904,M5,<NA>,229.65,2.083333,GLOBULAR_CLUSTER,Serpens Caput,5.6

In [20]:
df_combined = pd.concat([df_messier, df_caldwell, df_stars], ignore_index=True)

df_combined['id'] = 0
df_combined['observationStatus'] = 'NOT_OBSERVED'

In [21]:
df_combined.to_json('items.json', orient='records', lines=False)

In [22]:
df_combined['type'].value_counts()

STAR                 247
GALAXY                75
OPEN_CLUSTER          55
GLOBULAR_CLUSTER      47
PLANETARY_NEBULA      17
BRIGHT_NEBULA         12
NEBULA                 6
SUPERNOVA_REMNANT      3
ASTERISM               3
DARK_NEBULA            1
Name: type, dtype: int64